### ISSUE TITLE
Read in additional countries from AfroB

### ISSUE THREAD

**Issue by winklers** [winklers/language_lgbt#10]
Afrobarometer now has Round 6 data available for:
Egypt
Mozambique
Sao Tome Principe
South Africa

**Comment by jrnold** [comment]
How many are left?

**Comment by winklers** [comment]
Data for 4 countries has been released since we last worked on this. I can download those files and place them in the directory, but I've held off for now in case it will break our language matching code. Below is a list of the new countries and the ones that are still not released.
 
New countries:
- Egypt
- Mozambique
- Sao Tome Principe
- South Africa 

Still missing:
- Ethiopia (I don't think survey was completed)
- Gabon (I don't think survey was completed)
- Morocco (There is a survey questionnaire posted so I think the survey was completed)
- South Sudan (I don't think survey was completed)

**Comment by jrnold** [comment]
When you say not completed, do you mean ran out of funding and there will never be data?

**Comment by winklers** [comment]
For the countries that have a survey questionnaire posted, I assume the survey was conducted but the data is not released yet (but I can't confirm this). But for the countries with no questionnaire posted (Ethiopia & S. Sudan), I assume there was no attempt to conduct the survey in the country -- for whatever reason.
