### ISSUE TITLE
Match WALS to Afrobarometer languages

### ISSUE THREAD

**Issue by jrnold** [winklers/language_lgbt#3]
I created a `csv` file with the unique WALS languages as well as a few variables that may be useful to have on hand when matching those languages to the Afrobarometer languages. Fill in the column `afrobarometer_name` with the name in Afrobarometer. 

Then we can use this file to match Afrobarometer and WALS languages and merge the two datasets together.

**Comment by jrnold** [comment]
This dataset [Glottolog](http://glottolog.org/) has "Information about the different languages, dialects, and families of the world ('languoids')". This probably has all the information needed to link Afrobarometer to WALS, though from a glance, even Wikipedia looks pretty solid.

**Comment by jrnold** [comment]
And crazy measure of the day that I thought of looking through language databases: Use loanwords to proxy cultural influence: http://wold.clld.org/.

**Comment by jrnold** [comment]
Done

**Comment by winklers** [comment]
Matched WALS to Glottolog based on iso code and then to Afrobarometer based on name.
