### ISSUE TITLE
Clean up R scripts

### ISSUE THREAD

**Issue by jrnold** [winklers/language_lgbt#32]
There are multiple R scripts that aren't in `build.R`; if it isn't on `build.R` it shouldn't exist. If it doesn't run when run in sequence in `build.R` it probably has a bug. Since they aren't listed in order, I  no longer have any idea of what depends on what else. If you can't get `build.R` to run, file a bug report for me to fix. 

The Afrobarometer imputation should use `afrobarometer.rds`and not copy code from it - that is just error prone. If there are extra variables needed by `afrobarometer.rds` adjust the `afrobarometer.R` code.

Preferrably, these R scripts should produce one and only one `.rds` file with the same name as the `.R` file. That makes it easy to tell what script produces what output. If you need to save multiple objects, put them in a list and save that. You can always extract them from the list.

**Comment by winklers** [comment]
Okay, I will work on this. The only R scripts that I've added to the src file are the ones related to WALS and Afrob multiple imputation. I believe it is just 2 scripts, but will double check. I use the afrobarometer.rds and wals.rds file for these so it shouldn't be affecting any dependencies with what is in build.R already. 

Other than that, I've only been working on models in the analysis folder. I use the afrobarometer.rds file for each of these so there shouldn't be any weird dependencies there either. 

Please keep letting me know when you catch issues related to repo structuring ... I'm still learning the norms on this.

**Comment by jrnold** [comment]
there aren't norms on this :-( it's hard because research is heterogeneous.

**Comment by jrnold** [comment]
Sorry about this issue. I wrote it a little angry; as much annoyed by my own sloppiness as anything.
