### ISSUE TITLE
Lit Review

### ISSUE THREAD

**Issue by jrnold** [winklers/language_lgbt#4]
- [x] Check [Google Scholar](https://scholar.google.com/scholar?cites=10647454424808974569) cites of Chen for any relevant/recent citations. The paper is prominent enough that any recent work in econ/politics will cite it.

**Comment by winklers** [comment]
I have these saved in Zotero and can export them as a BibTex file.

**Comment by jrnold** [comment]
Okay, was there anything that we should know about?
