### ISSUE TITLE
Matching names

### ISSUE THREAD

**Issue by jrnold** [winklers/language_lgbt#7]
- match to WALS, ethnologue, glotto as in afrobarometer matches
- number of speakers 
- number of gender features of the WALS language
- is it extinct (remember to remove those)
- somehow match to any macrolanguages? 
- countries spoken in ... ?

**Comment by jrnold** [comment]
To proceed in matching, we can go in two steps.

1. Match Afrobarometer languages to ISO / Ethnologue Languages
2. Match ISO / Ethnologue languages to WALS 

This is easiest because the Ethnologue has a large list of alternative names, and the Ethnologue has pages for each country (e.g. [Nigeria](https://www.ethnologue.com/country/NG) that make it easy to find match the most widely spoken languages in the Afrobarometer data. Additionally, the Wikipedia pages of each country and often an additional page for the languages spoken in a country (e.g. [Languages of Benin](https://en.wikipedia.org/wiki/Languages_of_Benin)) link to the ISO/Ethnologue name of the language. 

1. Match as many of these as possible using alternative names and the countries in which the language is spoken.
2. Manually review these matches using the Ethnologue page and Wikipedia for the most widely spoken language
3. At least ensure all languages in which the Afrobarometer is given are matched.

Each WALS language has an associated ISO 639-3 code. However, these are not always equivalent. Additionally, each Afrobarometer language may match multiple ISO languages. Some ways to expand matches and reduce false negatives are

1. Match Afrobarometer language to any appropriate ISO macrolanguage
1. Calculate WALS stats for genus or family of the langauge and find matching ISO codes.

**Comment by winklers** [comment]
All names that can be matched to an ISO-639-3 should have one now.

**Comment by jrnold** [comment]
👍

**Comment by jrnold** [comment]
There seem to be a lot of names that have no matches but seem matchable. Can you make a note on anything that wasn't explicitly matched?

**Comment by winklers** [comment]
There should be a column called "no match". If there's text in that column, I couldn't determine a definite match. I count 27 languages that aren't matched.

**Comment by jrnold** [comment]
Awesome! I matched a few more, but it looks like we are in good shape. In a lot of cases it is unclear, but there are ways to handle uncertainty in our estimation.
